{% set name = "des-pizza-cutter-metadetect" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/beckermr/pizza-cutter-metadetect/archive/refs/tags/{{ version }}.tar.gz
  sha256: 16e57a0cd4ac70933ac99dc1a81e9a505643922a6e9f696656cc529574d6a1af

build:
  # this recipe is not noarch due to using the scripts kwarg w/ setuptools
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm !=6.3.1
    - setuptools_scm_git_archive
  run:
    - python
    - numpy
    - scipy
    - galsim
    - fitsio
    - pyyaml
    - numba
    - des-easyaccess
    - des-desmeds
    - meds >=0.9.14
    - ngmix >=2.0.6
    - click
    - esutil
    - sep
    - joblib
    - jinja2
    - tqdm
    - piff
    - cfitsio
    - metadetect >=0.6.0,<0.7.0a0
    - des-pizza-cutter >=0.5.1
    - des-sxdes
    - importlib_metadata
    - healsparse >=1.3.0

test:
  imports:
    - pizza_cutter_metadetect
  commands:
    - run-metadetect-on-slices --help
    - python -c "import pizza_cutter_metadetect; assert pizza_cutter_metadetect.__version__ == '{{ version }}'"

about:
  home: https://github.com/beckermr/pizza-cutter-metadetect
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: code to run metadetect on pizza cutter MEDs files

extra:
  recipe-maintainers:
    - beckermr
