{% set name = "des-pizza-cutter-metadetect" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/beckermr/pizza-cutter-metadetect/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2c4693cf6613c7b26dde764adc94f636d1d4babba0d14cdf0f0f73b3e90cbfb1

build:
  # this recipe is not noarch due to using the scripts kwarg w/ setuptools
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python
    - numpy
    - scipy
    - galsim
    - fitsio
    - pyyaml
    - numba
    - des-easyaccess
    - des-desmeds
    - meds
    - ngmix
    - click
    - esutil
    - sep
    - joblib
    - jinja2
    - tqdm
    - piff
    - cfitsio
    - metadetect
    - des-pizza-cutter
    - des-sxdes
    - importlib_metadata

test:
  imports:
    - pizza_cutter_metadetect
  commands:
    - run-metadetect-on-slices --help
    - python -c "import pizza_cutter_metadetect; assert pizza_cutter_metadetect.__version__ == '{{ version }}'"

about:
  home: https://github.com/beckermr/pizza-cutter-metadetect
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: code to run metadetect on pizza cutter MEDs files

extra:
  recipe-maintainers:
    - beckermr
